name: Build Bob

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DM_PACKAGES_URL: https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.0/
  BUILD_BRANCH: 1.9.6

jobs:
  build-bob:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Defold
        uses: actions/checkout@v4
        with:
          repository: defold/defold
          ref: ${{env.BUILD_BRANCH}}

      - name: Checkout patches
        uses: actions/checkout@v4
        with:
          path: patches

      - name: Apply patches
        run: git apply patches/all.patch

      - name: Install Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
        with:
          python-version: 3.12

      - name: Install Java
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
        with:
          java-version: '21.0.5+11.0.LTS'
          distribution: 'temurin'

      - name: Download archives
        uses: actions/download-artifact@v4
        with:
          name: tmp
          path: tmp
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: 12422712163

      - name: List archives
        run: ls -R tmp/archive

      - name: Build Bob
        run: ci/ci.sh bob

      - name: Check Bob version
        run: java -jar tmp/dynamo_home/share/java/bob.jar --version

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bob.jar
          path: |
            tmp/dynamo_home/share/java/bob.jar
